# Generated by Django 5.1.1 on 2024-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='es_psicologo',
            field=models.BooleanField(default=True),
        ),
    ]
