# Generated by Django 5.1.1 on 2024-10-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_psicologo_es_psicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
